server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

  mail:
    default-encoding: UTF-8
    host: localhost
    port: 2525
    username: username
    password: secret
    properties:
      mail:
        debug: true
        smtp:
          from: no-reply@wutsi.com
          auth: true
          starttls:
            enable: true
    test-connection: false

wutsi:
  client-id: wutsi-mail
  application:
    name: wutsi-mail
  platform:
    security:
      type: jwt
    tracing:
      client-id: ${wutsi.application.name}

logging:
  level:
    root: INFO
    com.wutsi.platform.mail: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


