spring:
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        debug: false

wutsi:
  client-id: wutsi-mail
  platform:
    security:
      type: jwt

